### ISSUE TITLE
Logaritmic scale 

### ISSUE THREAD

**Issue by jmartens** [home-assistant/analytics.home-assistant.io#27] opened 2021-04-01 13:52 UTC
Very nice to see the analytics, but I am a bit surprised by the logarithmic scale on the vertical axis as set at https://github.com/home-assistant/analytics.home-assistant.io/blob/5e7fb1c5c88e5a053175d205ac92908659b7e7f3/site/src/analytics-active-installations.ts#L59

Isn't that a bit out of the ordinary since normally this is only used in two cases. The first is to respond to skewness towards large values; i.e., cases in which one or a few points are much larger than the bulk of the data. The second is to show percent change or multiplicative factors.

We are not dealing with percent changes or multiplication factors and when the bulk of the installations is sending analytics I am not sure if a (large) skewness is to be expected.

**Comment by ludeeus** [comment] 2021-04-01 13:57
The difference between the total and the 4 different types will be too big. It's already started without that setting <https://3a97e587.analytics-home-assistant-io.pages.dev/> and it's expected to grow even further apart.

**Comment by jmartens** [comment] 2021-04-01 16:15
I would suggest a stacked area chart of the different types would be preferable giving the total implicitly. On Apr 1, 2021 15:58, Joakim Sørensen ***@***.***> wrote:
The difference between the total and the 4 different types will be too big. It's already started without that setting https://3a97e587.analytics-home-assistant-io.pages.dev/ and it's expected to grow even further apart.

**Comment by spacegaier** [comment] 2021-04-01 20:25
@jmartens Stacked charts in general are not a good solution for most uses cases and can be quite misleading, see e.g.: https://everydayanalytics.ca/2014/08/stacked-area-graphs-are-not-your-friend.html. Some chart libraries by design do not include them anymore (e.g. `uplot`).

**Comment by ludeeus** [comment] 2021-04-01 22:46
I'm thinking it should be split, time/line graph for total, and a pie chart for the current usage of the installation types.

**Comment by jmartens** [comment] 2021-04-02 09:00
I can live with that. I can see the drawbacks of my suggested stacked area chart, although I don't expect drastic ripples.Logarithmic axis are used in exceptional cases and most people are bad in reading them hence my suggestion to change. On Apr 2, 2021 00:47, Joakim Sørensen ***@***.***> wrote:
I'm thinking it should be split, time/line graph for total, and a pie chart for the current usage of the installation types.

**Comment by frenck** [comment] 2021-04-02 13:31
> I'm thinking it should be split, time/line graph for total, and a pie chart for the current usage of the installation types.

I do not agree with that. It removes a very interesting value from the page: Trend of the individual installation types.

I think an additional Pie to see the current OS usage, is really helpful (and is hard to see in the graph due to the log scaling).

**Comment by noxhirsch** [comment] 2021-04-07 06:41
> most people are bad in reading them hence my suggestion to change.

I agree with @jmartens:  The vast majority of people are not used to logaritmic scales and have a very hard time reading them or don't understand them at all. Many people won't even notice that it's logaritmic (I was very confused as I saw this graph the first time).
Now that we have the pie chart for installation types, I don't see a benefit in keeping the logaritmic scale.

**Comment by ludeeus** [comment] 2021-04-07 13:14
I made a revert PR for that change (#45) but as noted by @frenck that will not scale well for the future.
I'm closing both this issue and that PR now, since this is not considered an issue.

If  you have ideas or other feature requests for this page, please raise those on the forums <https://community.home-assistant.io/c/feature-requests/13>, thanks :+1:

**Closed by ludeeus** 2021-04-07 13:14 UTC

**Comment by CarlosGS** [comment] 2021-04-15 14:29
Log scale is still present, it seems the revert didn't make it to the main branch :S

(And I agree, the log graph makes it look like people had stopped enabling statistics)

**Comment by frenck** [comment] 2021-04-15 15:36
It's flat-looking now, because there is a shared 0 point at this moment. Once that goes out of the timeframe, things will start to look different. Give it 60 days.

**Comment by CarlosGS** [comment] 2021-04-15 16:14
You are very right - removing the first points it starts to look soo much smooth:
![Screenshot_20210415_175229](https://user-images.githubusercontent.com/1636266/114899581-5efae400-9e13-11eb-8847-f21e56296c2a.png)

Thanks though for adding a checkbox, it's great to have both options! ^^

Once there is more data, plotting the derivative might also be informative, it starts to show installation time patterns (day/night/weekends, impact of social media posts, etc).
_Sorry for the slight off topic, it's just a tiny curiosity and I don't want to bug you with any more issues or feature requests_ :angel: 
![Screenshot_20210415_181235](https://user-images.githubusercontent.com/1636266/114902502-2c9eb600-9e16-11eb-9ddd-33d4ffc2aefc.png)

Great job with the analytics, and thanks!! :)
